/* eslint-disable react-hooks/rules-of-hooks */
import Head from "next/head";
import { Navbar, Footer } from "../../../src/components/organisms";
import { Breadcrumbs } from "../../../src/components/molecules";
import { AdminProductDetail } from "../../../src/components/organisms";

export default function productDetail() {
  return (
    <div>
      <Head>
        <title>E-Commerce</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <AdminProductDetail />
      </main>
    </div>
  );
}
