import Head from "next/head";
import { CreateProductSection } from "../../../src/components/organisms";

export default function addProduct() {
  return (
    <div>
      <Head>
        <title>E-Commerce</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <CreateProductSection />
      </main>
    </div>
  );
}
