import Head from "next/head";

import { Admin } from "../../src/components/organisms";

export default function Home() {
  return (
    <div>
      <Head>
        <title>E-Commerce</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Admin />
      </main>
    </div>
  );
}
