import Head from "next/head";
import { FC } from "react";
import { ProductSection } from "../../src/components/organisms";

export default function products() {
  return (
    <div>
      <Head>
        <title>E-Commerce</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <ProductSection />{" "}
      </main>
    </div>
  );
}
