import Head from "next/head";
import { UsersSection } from "../../src/components/organisms";

export default function users() {
  return (
    <div>
      <Head>
        <title>E-Commerce</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <UsersSection />
      </main>
    </div>
  );
}
