import Head from "next/head";
import { Navbar, Footer, ProductDetail } from "../../src/components/organisms";
import { Breadcrumbs, Tabs } from "../../src/components/molecules";

export default function product() {
  return (
    <div>
      <Head>
        <title>E-Commerce</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navbar />
        <Breadcrumbs page=" Ürün Detayı" />
        <ProductDetail />
        <Tabs />

        <Footer />

        {/* <HeroSection /> */}
        {/* <Banner /> */}
      </main>
    </div>
  );
}
