import Head from "next/head";
import {
  Navbar,
  HeroSection,
  BannerSection,
  ProductCards,
  Footer,
  AdBannerSection,
} from "../src/components/organisms";
import { AbouthCard, BannerCard } from "../src/components/molecules";

export default function Home() {
  return (
    <div>
      <Head>
        <title>E-Commerce</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navbar />
        <HeroSection />
        <AbouthCard />
        <ProductCards />
        <BannerSection />
        <AdBannerSection />

        <Footer />
      </main>
    </div>
  );
}
