import Head from "next/head";
import { Breadcrumbs } from "../src/components/molecules";
import { Navbar, Footer } from "../src/components/organisms";
import { useAuth } from "../src/contexts/authContext";
import { useRouter } from "next/router";
import { useEffect } from "react";
export default function Profile() {
  const { user, logout, loggedIn } = useAuth();
  const router = useRouter();
  console.log("user", user);

  useEffect(() => {
    if (loggedIn) {
      return;
    } else {
      router.push("/auth/login");
    }
  });

  const handlelogout = async () => {
    logout(() => {
      router.push("/auth/login");
    });
  };
  return (
    <div>
      <Head>
        <title>E-Commerce</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navbar />
        <Breadcrumbs page="Tüm Ürünler" />
        <div>profile</div>
        <code>{JSON.stringify(user)}</code>
        <button onClick={handlelogout}>Çıkış</button>
        <Footer />
      </main>
    </div>
  );
}
